"""add_ai_model_to_user_profile

Revision ID: 196747c7fab8
Revises: d42cb75158a7
Create Date: 2026-07-21 16:38:06.253011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196747c7fab8'
down_revision: Union[str, Sequence[str], None] = 'd42cb75158a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('ai_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'ai_model')
    # ### end Alembic commands ###
