"""Add user_profile_id to data models

Revision ID: 3590d33e03ea
Revises: bd3443f9356b
Create Date: 2026-02-24 16:52:14.788370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3590d33e03ea'
down_revision: Union[str, Sequence[str], None] = 'bd3443f9356b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('user_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'charts', 'user_profile', ['user_profile_id'], ['id'])
    op.add_column('goals', sa.Column('user_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'goals', 'user_profile', ['user_profile_id'], ['id'])
    op.add_column('rest_days', sa.Column('user_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rest_days', 'user_profile', ['user_profile_id'], ['id'])
    op.add_column('workout', sa.Column('user_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workout', 'user_profile', ['user_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.drop_column('workout', 'user_profile_id')
    op.drop_constraint(None, 'rest_days', type_='foreignkey')
    op.drop_column('rest_days', 'user_profile_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'user_profile_id')
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.drop_column('charts', 'user_profile_id')
    # ### end Alembic commands ###
