"""Add WeeklyDigest model

Revision ID: 59d52b718a45
Revises: 64fad66804a7
Create Date: 2026-03-07 17:44:08.210648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d52b718a45'
down_revision: Union[str, Sequence[str], None] = '64fad66804a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_digest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_digest_user_sync_token'), 'weekly_digest', ['user_sync_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_digest_user_sync_token'), table_name='weekly_digest')
    op.drop_table('weekly_digest')
    # ### end Alembic commands ###
