"""Add sync_id column

Revision ID: 64fad66804a7
Revises: 8581a9eaf0d9
Create Date: 2026-03-04 22:56:19.715062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fad66804a7'
down_revision: Union[str, Sequence[str], None] = '8581a9eaf0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('conversation', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('conversation_message', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('rest_days', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('sync_id', sa.String(), nullable=True))
    op.add_column('workout', sa.Column('sync_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'sync_id')
    op.drop_column('user_profile', 'sync_id')
    op.drop_column('rest_days', 'sync_id')
    op.drop_column('goals', 'sync_id')
    op.drop_column('conversation_message', 'sync_id')
    op.drop_column('conversation', 'sync_id')
    op.drop_column('charts', 'sync_id')
    # ### end Alembic commands ###
