"""Change user_profile_id to user_sync_token

Revision ID: 8581a9eaf0d9
Revises: bdb9f66c9fbc
Create Date: 2026-03-02 16:32:03.024664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8581a9eaf0d9'
down_revision: Union[str, Sequence[str], None] = 'bdb9f66c9fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('user_sync_token', sa.String(), nullable=True))
    op.execute("UPDATE charts SET user_sync_token = (SELECT sync_token FROM user_profile WHERE user_profile.id = charts.user_profile_id)")
    op.alter_column('charts', 'user_sync_token', nullable=False)
    op.drop_constraint(op.f('charts_user_profile_id_fkey'), 'charts', type_='foreignkey')
    op.create_foreign_key(None, 'charts', 'user_profile', ['user_sync_token'], ['sync_token'])
    op.drop_column('charts', 'user_profile_id')
    op.add_column('conversation', sa.Column('user_sync_token', sa.String(), nullable=True))
    op.execute("UPDATE conversation SET user_sync_token = (SELECT sync_token FROM user_profile WHERE user_profile.id = conversation.user_profile_id)")
    op.drop_constraint(op.f('conversation_user_profile_id_fkey'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'user_profile', ['user_sync_token'], ['sync_token'], ondelete='CASCADE')
    op.drop_column('conversation', 'user_profile_id')
    op.add_column('goals', sa.Column('user_sync_token', sa.String(), nullable=True))
    op.execute("UPDATE goals SET user_sync_token = (SELECT sync_token FROM user_profile WHERE user_profile.id = goals.user_profile_id)")
    op.alter_column('goals', 'user_sync_token', nullable=False)
    op.drop_constraint(op.f('goals_user_profile_id_fkey'), 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'user_profile', ['user_sync_token'], ['sync_token'])
    op.drop_column('goals', 'user_profile_id')
    op.add_column('rest_days', sa.Column('user_sync_token', sa.String(), nullable=True))
    op.execute("UPDATE rest_days SET user_sync_token = (SELECT sync_token FROM user_profile WHERE user_profile.id = rest_days.user_profile_id)")
    op.alter_column('rest_days', 'user_sync_token', nullable=False)
    op.drop_constraint(op.f('rest_days_user_profile_id_fkey'), 'rest_days', type_='foreignkey')
    op.create_foreign_key(None, 'rest_days', 'user_profile', ['user_sync_token'], ['sync_token'])
    op.drop_column('rest_days', 'user_profile_id')
    op.add_column('workout', sa.Column('user_sync_token', sa.String(), nullable=True))
    op.execute("UPDATE workout SET user_sync_token = (SELECT sync_token FROM user_profile WHERE user_profile.id = workout.user_profile_id)")
    op.alter_column('workout', 'user_sync_token', nullable=False)
    op.drop_constraint(op.f('workout_user_profile_id_fkey'), 'workout', type_='foreignkey')
    op.create_foreign_key(None, 'workout', 'user_profile', ['user_sync_token'], ['sync_token'])
    op.drop_column('workout', 'user_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.create_foreign_key(op.f('workout_user_profile_id_fkey'), 'workout', 'user_profile', ['user_profile_id'], ['id'])
    op.drop_column('workout', 'user_sync_token')
    op.add_column('rest_days', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rest_days', type_='foreignkey')
    op.create_foreign_key(op.f('rest_days_user_profile_id_fkey'), 'rest_days', 'user_profile', ['user_profile_id'], ['id'])
    op.drop_column('rest_days', 'user_sync_token')
    op.add_column('goals', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key(op.f('goals_user_profile_id_fkey'), 'goals', 'user_profile', ['user_profile_id'], ['id'])
    op.drop_column('goals', 'user_sync_token')
    op.add_column('conversation', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_user_profile_id_fkey'), 'conversation', 'user_profile', ['user_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversation', 'user_sync_token')
    op.add_column('charts', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.create_foreign_key(op.f('charts_user_profile_id_fkey'), 'charts', 'user_profile', ['user_profile_id'], ['id'])
    op.drop_column('charts', 'user_sync_token')
    # ### end Alembic commands ###
