"""Add sync_token and user_profile_id

Revision ID: bdb9f66c9fbc
Revises: 3590d33e03ea
Create Date: 2026-02-28 16:53:32.888619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb9f66c9fbc'
down_revision: Union[str, Sequence[str], None] = '3590d33e03ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('user_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'user_profile', ['user_profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profile', sa.Column('sync_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_profile_sync_token'), 'user_profile', ['sync_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_sync_token'), table_name='user_profile')
    op.drop_column('user_profile', 'sync_token')
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'user_profile_id')
    # ### end Alembic commands ###
