"""add_api_key_and_provider_to_user_profile

Revision ID: d42cb75158a7
Revises: e7e09a2a18c2
Create Date: 2026-07-21 16:16:42.233025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42cb75158a7'
down_revision: Union[str, Sequence[str], None] = 'e7e09a2a18c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('ai_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'ai_provider')
    op.drop_column('user_profile', 'api_key')
    # ### end Alembic commands ###
