"""initial_migration

Revision ID: dda6c3f8d77e
Revises: 
Create Date: 2026-07-22 15:43:19.847791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda6c3f8d77e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_sync_token'), 'user_profile', ['sync_token'], unique=True)
    op.create_table('weekly_digest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_digest_user_sync_token'), 'weekly_digest', ['user_sync_token'], unique=False)
    op.create_table('charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('time_range', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_sync_token'], ['user_profile.sync_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_sync_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_sync_token'], ['user_profile.sync_token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('daily_skips', sa.Integer(), nullable=True),
    sa.Column('weekly_skips', sa.Integer(), nullable=True),
    sa.Column('weekly_workouts', sa.Integer(), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('weekly_calories', sa.Integer(), nullable=True),
    sa.Column('weekly_duration', sa.Integer(), nullable=True),
    sa.Column('skip_rate_goal', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_sync_token'], ['user_profile.sync_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rest_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_sync_token'], ['user_profile.sync_token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('user_sync_token', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('total_skips', sa.Integer(), nullable=False),
    sa.Column('avg_skips_per_minute', sa.Float(), nullable=True),
    sa.Column('trips', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_sync_token'], ['user_profile.sync_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_message')
    op.drop_table('workout')
    op.drop_table('rest_days')
    op.drop_table('goals')
    op.drop_table('conversation')
    op.drop_table('charts')
    op.drop_index(op.f('ix_weekly_digest_user_sync_token'), table_name='weekly_digest')
    op.drop_table('weekly_digest')
    op.drop_index(op.f('ix_user_profile_sync_token'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
